<a href="https://colab.research.google.com/github/junanote/test_deeplearning/blob/master/diff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sigmoid


In [1]:
import tensorflow as tf

In [4]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [5]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [6]:
b.numpy()


array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [7]:

inputs = tf.random.normal(shape=(1,3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.48806867, -0.29952946, -0.94208926]], dtype=float32)>

In [8]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.59024656, 0.2685245 , 0.14122896]], dtype=float32)>

In [9]:
outputs.numpy()

array([[0.59024656, 0.2685245 , 0.14122896]], dtype=float32)